### ISSUE TITLE
hostname: illegal option -- I

### ISSUE THREAD

**Issue by c1-g** [siddhpant/broo#1]
This is from running Broo itself, I've already ran the setup script.
On the man page, there's no mention of such option.
Is this needed?
FYI, I ran this on Artix Linux.

**Comment by siddhpant** [comment]
The man page lists the option: https://linux.die.net/man/1/hostname

Probably Artix has an old version.

Anyways, this shouldn't be a serious issue since everything has been set up. This comes at the end when the script tries to print the IP address which should be entered in Mumla to join.

You can use `hostname -i` (lowercase `i` here), or `ifconfig`, for the time being to get the IP. I'll look into this and fix this today.

**Comment by siddhpant** [comment]
Hey, can you try upgrading `inetutils`?

**Comment by siddhpant** [comment]
Arch has a very old version of `hostname`, so moved to using `ip`.

**Comment by c1-g** [comment]
Sorry, for the late reply. Yeah, it really is juts a minor inconvenience I just `ifconfig` to see the ip when I use it.

**Comment by siddhpant** [comment]
Yeah, sorry for that.

Pull the latest from main branch and update (either run setup again, or copy directly to /usr/local/bin), it should be fine now and you hopefully don't need to do anything extra.
