### ISSUE TITLE
i need help cause broo ruined my system

### ISSUE THREAD

**Issue by keibodkhslol** [siddhpant/broo#21]
it just straight up ruined my pc i got banned for asking for so much help from a discord server

so im just here to see if you can fix it

https://github.com/siddhpant/broo/assets/172603491/d0598c14-50b6-4ab3-a38c-4d4f6a044357

so i followed the guide on the github and installed it and started broo i didnt know if it work it stuck on instalazing broo

then i gave up and went to watch youtube and there was no sound

i check my settings/sounds/ there was nothing in the input or output channel just a dummy output

**Comment by keibodkhslol** [comment]
hi im back i followed this article https://ubuntuhandbook.org/index.php/2022/04/pipewire-replace-pulseaudio-ubuntu-2204/amp/   and it was fixed sorry

**Comment by keibodkhslol** [comment]
hello?

**Comment by siddhpant** [comment]
Can you show what `pavucontrol` shows? Search for it in the apps.

Also, does this happen after reboot and before using broo? Does it persist after force-sropping broo?

**Comment by keibodkhslol** [comment]
broo didn't even run it stuck on instalazing

**Comment by siddhpant** [comment]
Okay, but can you please provide the info that I requested? Otherwise I have no way of knowing anything.

Also, broo can get stuck only after you start broo. It does not start automatically.

**Comment by keibodkhslol** [comment]
it happens even after rebooting and dont doing anything for the pavucontrol
sorry im not home

**Comment by siddhpant** [comment]
Sure, no hurry. Please get back with the required info whenever you are free.

**Comment by keibodkhslol** [comment]
[image: Screenshot from 2024-06-13 12-16-26.png]heres pavucontrol

**Comment by siddhpant** [comment]
There is no photo. It seems drag and drop didn't work.

Also, please post all the info I requested above. Also all pavucontrol tabs.

**Comment by feeRnt** [comment]
I had some similar issue, that may have been related to a botched use of broo.
(This happened some months back so my memory isn't fully fresh on how it happened).
Maybe it was caused by not stopping an instance of broo before shutting off the system.

The next restart there was no audio,  (PopOS 22.04), and further restarts did not help.
I tried different solutions, but what fixed it was 

`systemctl --user restart wireplumber.service
Failed to restart wireplumber.service: Unit pipewire.service is masked.`

so I did 
`systemctl --user unmask pipewire.service
systemctl --user restart wireplumber.service `

and then it was fixed.

I'm not sure how it happened. Looking at my logs it seems that sometime before the system shutdown I had done 

`sudo systemctl --user restart pipewire.service
sudo systemctl stop mumble-server.service`
for some personal testing

which in my understanding shouldn't have broken anything either, but I'm posting this here just in case someone  else's audio stops working randomly for some reason aha.
I don't know why the pipewire service got masked, but that's what worked for me.

**Comment by siddhpant** [comment]
Thanks @feeRnt for the write-up!

Going by what OP said and you posted, it smells like a broken update in the background to me.

There is indeed an apt update/install when locally building mumble during broo setup, which could be a contributing factor (the setup doesn't install pipewire related things though).

**Comment by feeRnt** [comment]
Thanks for the response!
I just checked the setup_broo script and I did have Mumble installed during the first launch (this audio issue happened after installing broo for the first time btw. Though I had some difficulty using it), so I think I wasn't prompted for the broo building.

I think now I do remember issuing a SIGINT (ctrl C) when it asked if I wanted to update my dependencies, and I don't know  if I did any other weird things trying to use it afterwqards (more ctrl Cs). 

Either way since this doesn't seem to be reproducible it's maybe not worth digging, but thanks for your input still!
