### ISSUE TITLE
Doesn't work on ArchLinux with pipewire.

### ISSUE THREAD

**Issue by Tails-OS** [siddhpant/broo#5]
Hi, I followed the instructions to run your script, but nothing works.
Unless the "Monitor of Broo" appears, but it does not reproduce the sound... But I hear my voice from mumble, which is transmitted through the phone.
Btw, if I terminate the script, then alsa_output remains as an input device, which transmits the sound of the system itself.

Please help me to solve this problem. Thank you in advance
![Снимок экрана от 2022-02-26 21-12-36](https://user-images.githubusercontent.com/63146525/155855061-bffc64b3-69a8-4732-b030-6b827115e81e.png)
![Снимок экрана от 2022-02-26 21-16-06](https://user-images.githubusercontent.com/63146525/155855060-dc6fa3b4-d607-40cc-87ee-e0a7d0f7973d.png)
![Снимок экрана от 2022-02-26 21-19-05](https://user-images.githubusercontent.com/63146525/155855062-0056c261-7176-4537-8491-666786d90ebe.png)
### **(./setup_broo: line 209: 1747 Segmentation fault (memory stack flushed to disk) mumble > /dev/null 2>&1)**
![Снимок экрана от 2022-02-26 21-22-06](https://user-images.githubusercontent.com/63146525/155855063-d3023d69-b9e5-4e3c-9b20-d2b7e6cb5c7d.png)

**Comment by siddhpant** [comment]
First of all, sorry for those ugly `which` outputs. I didn't know it wasn't standard (and thought it just returns status code). I have moved to POSIX `command`, please update and use setup again.

---

> Unless the "Monitor of Broo" appears, but it does not reproduce the sound... But I hear my voice from mumble, which is transmitted through the phone.

Weird, because I specifically cope for it in [the script itself](https://github.com/siddhpant/broo/blob/main/broo#L104). Can you tell me the output/behaviour of the following commands after setting up?

```
pactl set-sink-volume Broo 0
pactl set-default-source Broo
pactl move-sink-input $(get_mumble_sink_input_index) Broo
```

---

> (./setup_broo: line 209: 1747 Segmentation fault (memory stack flushed to disk) mumble > /dev/null 2>&1)

Please reinstall Mumble if this persists, or build from source. This is a problem with Mumble, you should make an issue in https://github.com/mumble-voip/issues if this persists.

Also, line 209 doesn't call mumble. Check your modifications to the scripts too.

---

> Btw, if I terminate the script, then alsa_output remains as an input device, which transmits the sound of the system itself.

That's the default behavior on Linux. Here, just the name of the stereo sink is changed in Discord, and I think maybe the name change is actually Electron's problem (Discord is made on Electron). I don't know how to change the name, any help would be appreciated.

Here's how it looks even before using Broo.

![image](https://user-images.githubusercontent.com/25429745/155857699-a18c2258-a1c8-49ac-8a9b-6de5346060db.png)

**Comment by siddhpant** [comment]
Stale issue, renaming to make it explicit

**Comment by siddhpant** [comment]
Closing because no reply.
